### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by CPyeah** [Peng-YM/LeetCode-Anki#10]
I run `python3 main_cn.py`
I uesd leetcode-cn, and I login by phone verify code.
Then, this exception happend. I don't know why.
```
Traceback (most recent call last):
  File "/Users/chengpeng/xiedaimala/LeetCode-Anki/main_cn.py", line 11, in <module>
    worker.fetch_accepted_problems()
  File "/Users/chengpeng/xiedaimala/LeetCode-Anki/crawler_cn.py", line 72, in fetch_accepted_problems
    response = self.session.get("https://leetcode-cn.com/api/problems/all/")
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```
<img width="950" alt="image" src="https://user-images.githubusercontent.com/9623028/187632008-941dc890-5393-4d01-a6c2-592164f5b318.png">

**Comment by keniushadu** [comment]
域名替换一下 leetcode-cn.com 替换成 leetcode.cn
