### ISSUE TITLE
Does not support Chrome version 109.0.5414.119

### ISSUE THREAD

**Issue by chang-you** [Peng-YM/LeetCode-Anki#13]
I run `python3 main.py` and run into the below error:
```
😎 Starting browser login..., please fill the login form
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    worker.login()
  File "/Users/yoci642/Desktop/Dev/LeetCode-Anki/crawler.py", line 42, in login
    browser = webdriver.Chrome(executable_path="./vendor/chromedriver")
  File "/Users/yoci642/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/yoci642/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/yoci642/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/yoci642/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/yoci642/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 109.0.5414.119 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

I tried downloading Chrome 97 again but this old version cannot run in the latest macOS Ventura (Version 13.2.1)

**Comment by zerone0x** [comment]
You could try to download latest chromedriver to fix it
