### ISSUE TITLE
urllib issue

### ISSUE THREAD

**Issue by arasouli91** [Peng-YM/LeetCode-Anki#15]
PS C:\Users\v-arasouli\Downloads\LeetCode-Anki-master\LeetCode-Anki-master> python3 main.py            
Traceback (most recent call last):
  File "C:\Users\v-arasouli\Downloads\LeetCode-Anki-master\LeetCode-Anki-master\main.py", line 2, in <module>
    from crawler import LeetCodeCrawler
  File "C:\Users\v-arasouli\Downloads\LeetCode-Anki-master\LeetCode-Anki-master\crawler.py", line 7, in <module>
    import requests
  File "C:\Users\v-arasouli\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\v-arasouli\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\v-arasouli\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\v-arasouli\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by zerone0x** [comment]
You need to run the script on python virtual environment
