### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by chenchenchen7** [Peng-YM/LeetCode-Anki#4]
请问这是什么问题呀 谢谢！
F:\LeetCode-Anki-master>python main.py
😎 Starting browser login..., please fill the login form
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    worker.login()
  File "F:\LeetCode-Anki-master\crawler.py", line 42, in login
    browser = webdriver.Chrome(executable_path="./vendor/chromedriver")
  File "C:\Users\76731\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\76731\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\76731\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\76731\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by moon290** [comment]
同问~

**Comment by moon290** [comment]
更新了浏览器驱动解决了~

**Comment by moon290** [comment]
但是登陆不成功，这是什么原因呢
![20210320181534](https://user-images.githubusercontent.com/34809450/111866419-44feea80-89a8-11eb-8c0a-4464c8b9dfc7.png)

**Comment by Alfred212121** [comment]
同样，把浏览器驱动配置成一致后还是不行

**Comment by Haishanliu** [comment]
遇到同样的问题，没法使用

**Comment by che808** [comment]
same problem
